/**
 * ⚡ JALANKAN SALAH SATU FUNGSI INI DARI DROPDOWN APPS SCRIPT:
 * - tambahKolomCreditGaleri (Bahasa Indonesia)
 * - addAutoSelectCreditColumn (Bahasa Inggris)
 * Untuk membuat kolom autoselect_credits otomatis di spreadsheet sheet 'Galeri'
 */
function tambahKolomCreditGaleri() {
  return setupAutoSelectCreditColumn();
}

function addAutoSelectCreditColumn() {
  return setupAutoSelectCreditColumn();
}

function setupAutoSelectCreditColumn() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Galeri') || ss.getSheetByName('Gallery') || ss.getSheetByName('galeri');
  if (!sheet) {
    Logger.log("Error: Sheet 'Galeri' atau 'Gallery' tidak ditemukan.");
    return "Error: Sheet 'Galeri' atau 'Gallery' tidak ditemukan.";
  }
  
  var lastCol = Math.max(1, sheet.getLastColumn());
  var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
  var colIdx = -1;
  
  for (var i = 0; i < headers.length; i++) {
    var h = String(headers[i] || '').trim().toLowerCase();
    if (h === 'autoselect_credits' || h === 'autoselectcredits' || h === 'credits' || h === 'credit') {
      colIdx = i + 1;
      break;
    }
  }
  
  if (colIdx === -1) {
    colIdx = lastCol + 1;
    sheet.getRange(1, colIdx).setValue('autoselect_credits');
  }
  
  var lastRow = sheet.getLastRow();
  var filledCount = 0;
  if (lastRow > 1) {
    for (var r = 2; r <= lastRow; r++) {
      var val = sheet.getRange(r, colIdx).getValue();
      if (val === '' || val === null || val === undefined) {
        sheet.getRange(r, colIdx).setValue(1);
        filledCount++;
      }
    }
  }
  
  SpreadsheetApp.flush();
  var msg = "BERHASIL! Kolom 'autoselect_credits' aktif di kolom ke-" + colIdx + " dan diisi 1 credit untuk " + filledCount + " galeri.";
  Logger.log(msg);
  return msg;
}


// Generated by GAS WebApp Builder | Created by @farhanalfaizi

/**
 * Konfigurasi Utama
 */
var CACHE_EXPIRATION = 28800; // 8 jam

/**
 * doGet - Entry Point Web App dengan pre-loading data & optimasi kecepatan
 */
function doGet(e) {
  // Support API JSON calls dari frontend / Vercel
  if (e && e.parameter && (e.parameter.action === 'getGalleryAutoSelectCredits' || e.parameter.api === 'getGalleryCredits')) {
    var resGal = getGalleryAutoSelectCredits(e.parameter.gal || e.parameter.galId);
    var strGal = JSON.stringify(resGal);
    if (e.parameter.callback) {
      return ContentService.createTextOutput(e.parameter.callback + '(' + strGal + ');').setMimeType(ContentService.MimeType.JAVASCRIPT);
    }
    return ContentService.createTextOutput(strGal).setMimeType(ContentService.MimeType.JSON);
  }
  if (e && e.parameter && (e.parameter.action === 'deductGalleryAutoSelectCredit' || e.parameter.api === 'deductGalleryCredit')) {
    var resDeduct = deductGalleryAutoSelectCredit(e.parameter.gal || e.parameter.galId);
    var strDeduct = JSON.stringify(resDeduct);
    if (e.parameter.callback) {
      return ContentService.createTextOutput(e.parameter.callback + '(' + strDeduct + ');').setMimeType(ContentService.MimeType.JAVASCRIPT);
    }
    return ContentService.createTextOutput(strDeduct).setMimeType(ContentService.MimeType.JSON);
  }
  if (e && e.parameter && (e.parameter.action === 'setGalleryAutoSelectCredits' || e.parameter.api === 'setGalleryCredits' || e.parameter.action === 'updateGalleryCredit')) {
    var resSet = setGalleryAutoSelectCredits(e.parameter.gal || e.parameter.galId, e.parameter.credits || e.parameter.c);
    var strSet = JSON.stringify(resSet);
    if (e.parameter.callback) {
      return ContentService.createTextOutput(e.parameter.callback + '(' + strSet + ');').setMimeType(ContentService.MimeType.JAVASCRIPT);
    }
    return ContentService.createTextOutput(strSet).setMimeType(ContentService.MimeType.JSON);
  }

  // Routing ke halaman khusus AutoSelect
  if (e && e.parameter && e.parameter.page === 'autoselect') {
    return HtmlService.createTemplateFromFile('AutoSelect')
      .evaluate()
      .setTitle('AutoSelect File - Ttwins Selection')
      .addMetaTag('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5.0')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }

  // 2. Routing khusus ke halaman Galeri Klien (Client.html)
  // Diakses ketika parameter page bernilai 'client' atau 'klien', atau langsung membawa parameter galeri
  var isClientPage = false;
  if (e && e.parameter) {
    var p = e.parameter;
    if (p.page === 'client' || p.page === 'klien' || p.client === 'true') {
      isClientPage = true;
    } else if ((p.galeri || p.client_galeri || p.g || p.id) && p.page !== 'admin' && p.page !== 'studio' && p.page !== 'autoselect') {
      isClientPage = true;
    }
  }

  var defaultGoogleSitesUrl = 'https://sites.google.com/view/ttwinselect/client';
  var defaultCustomDomain = PropertiesService.getScriptProperties().getProperty('CUSTOM_VERCEL_DOMAIN') || '';
  if (!defaultCustomDomain && e && e.parameter && e.parameter.v_domain) {
    defaultCustomDomain = String(e.parameter.v_domain).trim();
  }

  if (isClientPage) {
    var clientTemplate = HtmlService.createTemplateFromFile('Client');
    clientTemplate.runtimeMode = 'production';
    clientTemplate.webAppUrl = ScriptApp.getService().getUrl();
    clientTemplate.googleSitesUrl = defaultGoogleSitesUrl;
    clientTemplate.customDomain = defaultCustomDomain;

    var initialGaleri = '';
    if (e && e.parameter) {
      initialGaleri = String(e.parameter.galeri || e.parameter.client_galeri || e.parameter.g || e.parameter.id || '').trim();
    }

    var initialGalleryData = null;
    if (initialGaleri) {
      try {
        var preResult = getPublicGallery(initialGaleri);
        if (preResult && preResult.success) {
          initialGalleryData = preResult;
        }
      } catch (err) {
        initialGalleryData = null;
      }
    }
    clientTemplate.initialGaleri = initialGaleri;
    clientTemplate.initialGalleryData = initialGalleryData;

    var clientPageTitle = 'Seleksi Foto Klien - Ttwins Selection';
    if (initialGalleryData && initialGalleryData.gallery) {
      var g = initialGalleryData.gallery;
      clientPageTitle = (g.judul_acara || g.nama_client || 'Galeri') + ' - Seleksi Foto';
    }

    return clientTemplate.evaluate()
      .setTitle(clientPageTitle)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5.0')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }

  // 3. DEFAULT UTAMA: Halaman Index.html (Halaman Utama / Landing Page & Studio Fotografer)
  var template = HtmlService.createTemplateFromFile('Index');
  template.runtimeMode = 'production';

  // Ambil URL WebApp secara langsung dan akurat dari sistem Google
  var webAppUrl = ScriptApp.getService().getUrl();
  template.webAppUrl = webAppUrl;
  template.googleSitesUrl = defaultGoogleSitesUrl;
  template.customDomain = defaultCustomDomain;

  var initialGaleri = '';
  var initialGalleryData = null;
  if (e && e.parameter) {
    initialGaleri = String(e.parameter.galeri || e.parameter.client_galeri || e.parameter.g || e.parameter.id || '').trim();
    if (initialGaleri) {
      try {
        var preResult = getPublicGallery(initialGaleri);
        if (preResult && preResult.success) {
          initialGalleryData = preResult;
        }
      } catch (err) {
        initialGalleryData = null;
      }
    }
  }
  template.initialGaleri = initialGaleri;
  template.initialGalleryData = initialGalleryData;

  var pageTitle = 'Gallery Selection Pilihin';
  if (initialGalleryData && initialGalleryData.gallery) {
    var g = initialGalleryData.gallery;
    pageTitle = (g.judul_acara || g.nama_client || 'Galeri') + ' - Pilihin';
  }

  return template.evaluate()
    .setTitle(pageTitle)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5.0')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}


/**
 * Setup Database & Admin Awal
 */
function setupDatabase() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = {
    'User': ['id_user', 'nama', 'email', 'role', 'paket', 'username', 'password', 'wa_vendor', 'logo_vendor', 'custom_domain'],
    'Galeri': ['id_galeri', 'id_fotografer', 'nama_client', 'judul_acara', 'link_drive', 'batas_foto', 'deadline', 'tanggal_acara', 'highlight', 'email_client', 'whatsapp_client', 'izin_download', 'status', 'whatsapp_vendor', 'nama_vendor', 'kirim_tanpa_drive'],
    'Foto': ['id_foto', 'id_galeri', 'nama_file', 'url_foto', 'nomor_foto', 'nama_folder'],
    'Seleksi': ['id_seleksi', 'id_galeri', 'id_foto', 'pesan_client', 'tanggal_pilih'],
    'Job': ['id_job', 'id_fotografer', 'nama_client', 'tanggal_acara', 'status'],
    'TempFolder': ['id_folder', 'id_galeri', 'nama_folder', 'url_folder', 'tanggal_buat', 'tanggal_kadaluarsa', 'status'],
    'AuditLog': ['timestamp', 'action', 'user', 'details']
  };

  for (var name in sheets) {
    var sheet = ss.getSheetByName(name);
    if (!sheet) {
      sheet = ss.insertSheet(name);
      sheet.appendRow(sheets[name]);
      sheet.setFrozenRows(1);
    } else {
      var lastCol = Math.max(1, sheet.getLastColumn());
      var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
      for (var colIdx = 0; colIdx < sheets[name].length; colIdx++) {
        var colName = sheets[name][colIdx];
        if (headers.indexOf(colName) === -1) {
          lastCol++;
          sheet.getRange(1, lastCol).setValue(colName);
          headers.push(colName);
        }
      }
    }
  }

  // Setup Default Admin
  var userSheet = ss.getSheetByName('User');
  var users = userSheet.getDataRange().getValues();
  var adminExists = false;
  for (var i = 1; i < users.length; i++) {
    if (users[i][5] === 'admin') {
      adminExists = true;
      break;
    }
  }

  if (!adminExists) {
    var adminPass = hashPassword('Admin@2026');
    userSheet.appendRow(['U' + new Date().getTime(), 'Fotografer Studio', 'studio@email.com', 'Fotografer', 'PRO', 'admin', adminPass]);
  }
}

/**
 * Keamanan & Helper
 */
function hashPassword(password) {
  var signature = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password);
  var hash = '';
  for (var i = 0; i < signature.length; i++) {
    var byte = signature[i];
    if (byte < 0) byte += 256;
    var byteStr = byte.toString(16);
    if (byteStr.length == 1) byteStr = '0' + byteStr;
    hash += byteStr;
  }
  return hash;
}

function generateSessionToken() {
  return Utilities.getUuid();
}

function sanitizeInput(input) {
  if (typeof input !== 'string') return input;
  return input.replace(/</g, "&lt;").replace(/>/g, "&gt;").trim();
}

function getMapFromHeaders(headers) {
  var map = {};
  if (!headers || !headers.length) return map;
  for (var i = 0; i < headers.length; i++) {
    var raw = String(headers[i]).trim();
    if (!raw) continue;
    map[raw] = i;
    var lower = raw.toLowerCase();
    map[lower] = i;
    var norm = lower.replace(/[\s\-_]+/g, '');
    map[norm] = i;
  }
  if (map['autoselect_credits'] === undefined) {
    var aliases = ['autoselectcredits', 'autoselect_credit', 'autoselectcredit', 'credit_autoselect', 'creditautoselect', 'credit', 'credits'];
    for (var a = 0; a < aliases.length; a++) {
      if (map[aliases[a]] !== undefined) {
        map['autoselect_credits'] = map[aliases[a]];
        break;
      }
    }
  }
  return map;
}

function getColumnMap(sheet, optHeaders) {
  var headers = optHeaders;
  if (!headers || !headers.length) {
    var lastCol = Math.max(1, sheet.getLastColumn());
    headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
  }
  return getMapFromHeaders(headers);
}

function ensurePhotoFolderColumn(photoSheet, optMap) {
  var map = optMap || getColumnMap(photoSheet);
  if (map['nama_folder'] === undefined) {
    var lastCol = Math.max(1, photoSheet.getLastColumn());
    photoSheet.getRange(1, lastCol + 1).setValue('nama_folder');
    return getColumnMap(photoSheet);
  }
  return map;
}

function ensureGalleryVendorColumn(galSheet, optMap) {
  var lastCol = Math.max(1, galSheet.getLastColumn());
  var headers = galSheet.getRange(1, 1, 1, lastCol).getValues()[0];
  var map = getMapFromHeaders(headers);
  var nextCol = headers.length + 1;
  var changed = false;

  var requiredCols = ['whatsapp_vendor', 'nama_vendor', 'kirim_tanpa_drive', 'autoselect_credits'];
  for (var c = 0; c < requiredCols.length; c++) {
    var colName = requiredCols[c];
    if (map[colName] === undefined) {
      galSheet.getRange(1, nextCol).setValue(colName);
      headers.push(colName);
      map[colName] = nextCol - 1;
      nextCol++;
      changed = true;
    }
  }

  if (changed) {
    SpreadsheetApp.flush();
    return getColumnMap(galSheet);
  }
  return map;
}

function ensureUserColumns(userSheet, optMap) {
  var map = optMap || getColumnMap(userSheet);
  var changed = false;
  var required = ['wa_vendor', 'logo_vendor', 'custom_domain'];
  for (var i = 0; i < required.length; i++) {
    var col = required[i];
    if (map[col] === undefined) {
      var lastCol = Math.max(1, userSheet.getLastColumn());
      userSheet.getRange(1, lastCol + 1).setValue(col);
      changed = true;
      map = getColumnMap(userSheet);
    }
  }
  return map;
}


function logAction(action, user, details) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('AuditLog');
    sheet.appendRow([new Date().toISOString(), action, user || 'System', JSON.stringify(details)]);
  } catch(e){}
}

function safeDateFormat(dateObj) {
  if (!dateObj) return '';
  if (typeof dateObj === 'string') return dateObj;
  try { return dateObj.toISOString(); } catch(e) { return String(dateObj); }
}

/**
 * Autentikasi
 */
function checkRateLimit(username) {
  var cache = CacheService.getScriptCache();
  var fails = cache.get('login_fail_' + username);
  if (fails && parseInt(fails) >= 5) {
    return false;
  }
  return true;
}

function recordLoginFailure(username) {
  var cache = CacheService.getScriptCache();
  var key = 'login_fail_' + username;
  var fails = cache.get(key);
  fails = fails ? parseInt(fails) + 1 : 1;
  cache.put(key, fails.toString(), 900); // 15 menit
}

function loginUser(username, password) {
  try {
    var u = sanitizeInput(username);
    if (!u) {
      return { success: false, message: 'Username tidak boleh kosong.' };
    }
    if (!checkRateLimit(u)) {
      return { success: false, message: 'Terlalu banyak percobaan. Coba lagi dalam 15 menit.' };
    }

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('User');
    if (!sheet) {
      setupDatabase();
      sheet = ss.getSheetByName('User');
    }

    var map = ensureUserColumns(sheet);
    var data = sheet.getDataRange().getValues();
    var hashedPass = hashPassword(password);
    var cleanUser = String(u).trim().toLowerCase();

    // Pastikan database terisi admin awal jika baris hanya header
    if (data.length <= 1) {
      setupDatabase();
      sheet = ss.getSheetByName('User');
      map = ensureUserColumns(sheet);
      data = sheet.getDataRange().getValues();
    }

    for (var i = 1; i < data.length; i++) {
      var rowUser = String(data[i][map['username']] || '').trim().toLowerCase();
      var rowPass = String(data[i][map['password']] || '');

      var passMatch = (rowPass === hashedPass);
      // Dukung password default 'bismillah', 'Admin@2026', atau 'admin' untuk user admin
      if (!passMatch && cleanUser === 'admin') {
        if (password === 'bismillah' || password === 'Admin@2026' || password === 'admin') {
          passMatch = true;
          try {
            sheet.getRange(i + 1, map['password'] + 1).setValue(hashedPass);
          } catch(err) {}
        }
      }

      if (rowUser === cleanUser && passMatch) {
        var token = generateSessionToken();
        var cache = CacheService.getScriptCache();
        
        var savedDomain = (map['custom_domain'] !== undefined ? String(data[i][map['custom_domain']] || '').trim() : '') ||
                          PropertiesService.getScriptProperties().getProperty('CUSTOM_VERCEL_DOMAIN') || '';

        var userObj = {
          id_user: data[i][map['id_user']] || 'U1',
          nama: data[i][map['nama']] || 'Fotografer Studio',
          email: data[i][map['email']] || 'studio@email.com',
          role: data[i][map['role']] || 'Fotografer',
          paket: data[i][map['paket']] || 'PRO',
          username: map['username'] !== undefined ? data[i][map['username']] : cleanUser,
          wa: map['wa_vendor'] !== undefined ? data[i][map['wa_vendor']] : '',
          logo: map['logo_vendor'] !== undefined ? data[i][map['logo_vendor']] : '',
          custom_domain: savedDomain
        };
        
        cache.put('session_' + token, JSON.stringify(userObj), CACHE_EXPIRATION);
        CacheService.getScriptCache().remove('login_fail_' + u);
        logAction('LOGIN', userObj.id_user, 'Success');
        
        return { success: true, token: token, user: userObj };
      }
    }

    // Jika user admin belum terdaftar, buatkan otomatis
    if (cleanUser === 'admin' && (password === 'bismillah' || password === 'Admin@2026' || password === 'admin')) {
      var newUserId = 'U' + new Date().getTime();
      var newAdminPass = hashPassword(password);
      var savedDomain = PropertiesService.getScriptProperties().getProperty('CUSTOM_VERCEL_DOMAIN') || '';
      sheet.appendRow([newUserId, 'Fotografer Studio', 'studio@email.com', 'Fotografer', 'PRO', 'admin', newAdminPass, '', '', savedDomain]);
      
      var newAdminObj = {
        id_user: newUserId,
        nama: 'Fotografer Studio',
        email: 'studio@email.com',
        role: 'Fotografer',
        paket: 'PRO',
        username: 'admin',
        wa: '',
        logo: '',
        custom_domain: savedDomain
      };
      var token = generateSessionToken();
      var cache = CacheService.getScriptCache();
      cache.put('session_' + token, JSON.stringify(newAdminObj), CACHE_EXPIRATION);
      logAction('LOGIN', newUserId, 'AutoCreatedAdmin');
      return { success: true, token: token, user: newAdminObj };
    }
    
    recordLoginFailure(u);
    return { success: false, message: 'Username atau password salah (Demo: admin/bismillah).' };
  } catch (e) {
    return { success: false, message: 'Gagal login: ' + e.message };
  }
}

function validateSession(token) {
  if (!token) return null;
  var cache = CacheService.getScriptCache();
  var userStr = cache.get('session_' + token);
  if (userStr) {
    return JSON.parse(userStr);
  }
  return null;
}

function verifyToken(token) {
  return validateSession(token);
}

function logout(token) {
  if (token) {
    var cache = CacheService.getScriptCache();
    cache.remove('session_' + token);
  }
  return { success: true };
}

function updateUserSettings(token, payload) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('User');
    var map = ensureUserColumns(sheet);
    var data = sheet.getDataRange().getValues();

    var rowIndex = -1;
    for (var i = 1; i < data.length; i++) {
      if (data[i][map['id_user']] === user.id_user) {
        rowIndex = i + 1;
        break;
      }
    }

    if (rowIndex === -1) return { success: false, message: 'User tidak ditemukan.' };

    if (payload.nama) sheet.getRange(rowIndex, map['nama'] + 1).setValue(sanitizeInput(payload.nama));
    if (payload.wa !== undefined) sheet.getRange(rowIndex, map['wa_vendor'] + 1).setValue(sanitizeInput(payload.wa));
    if (payload.email) sheet.getRange(rowIndex, map['email'] + 1).setValue(sanitizeInput(payload.email));
    if (payload.password) sheet.getRange(rowIndex, map['password'] + 1).setValue(hashPassword(payload.password));

    // Simpan Domain Kustom / Vercel ke database User dan ScriptProperties
    var cleanDomain = '';
    if (payload.custom_domain !== undefined) {
      cleanDomain = String(payload.custom_domain || '').trim().replace(/\/+$/, '');
      if (cleanDomain && !/^https?:\/\//i.test(cleanDomain)) {
        cleanDomain = 'https://' + cleanDomain;
      }
      sheet.getRange(rowIndex, map['custom_domain'] + 1).setValue(cleanDomain);
      try {
        if (cleanDomain) {
          PropertiesService.getScriptProperties().setProperty('CUSTOM_VERCEL_DOMAIN', cleanDomain);
        } else {
          PropertiesService.getScriptProperties().deleteProperty('CUSTOM_VERCEL_DOMAIN');
        }
      } catch (errProp) {}
    } else {
      cleanDomain = (map['custom_domain'] !== undefined ? String(data[rowIndex - 1][map['custom_domain']] || '').trim() : '') ||
                    PropertiesService.getScriptProperties().getProperty('CUSTOM_VERCEL_DOMAIN') || '';
    }
    
    var logoUrl = null;
    if (payload.logoData && payload.logoMime) {
      logoUrl = 'data:' + payload.logoMime + ';base64,' + payload.logoData;
      sheet.getRange(rowIndex, map['logo_vendor'] + 1).setValue(logoUrl);
    }

    // Update session data di cache langsung
    var updatedUser = {
      id_user: user.id_user,
      nama: payload.nama || user.nama,
      email: payload.email || user.email,
      role: user.role,
      paket: user.paket,
      username: user.username,
      wa: payload.wa !== undefined ? payload.wa : user.wa,
      logo: logoUrl || user.logo,
      custom_domain: cleanDomain
    };
    CacheService.getScriptCache().put('session_' + token, JSON.stringify(updatedUser), CACHE_EXPIRATION);

    logAction('UPDATE_SETTINGS', user.id_user, 'Update Profile & Domain');
    return { success: true, logoUrl: logoUrl, customDomain: cleanDomain, user: updatedUser };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    try { lock.releaseLock(); } catch(e) {}
  }
}

function getUserSettings(token) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('User');
    var map = ensureUserColumns(sheet);
    var data = sheet.getDataRange().getValues();
    var foundUser = null;
    for (var i = 1; i < data.length; i++) {
      if (data[i][map['id_user']] === user.id_user) {
        var domain = (map['custom_domain'] !== undefined ? String(data[i][map['custom_domain']] || '').trim() : '') ||
                     PropertiesService.getScriptProperties().getProperty('CUSTOM_VERCEL_DOMAIN') || '';
        foundUser = {
          id_user: data[i][map['id_user']],
          nama: data[i][map['nama']] || '',
          email: data[i][map['email']] || '',
          role: data[i][map['role']] || '',
          paket: data[i][map['paket']] || '',
          username: data[i][map['username']] || '',
          wa: map['wa_vendor'] !== undefined ? (data[i][map['wa_vendor']] || '') : '',
          logo: map['logo_vendor'] !== undefined ? (data[i][map['logo_vendor']] || '') : '',
          custom_domain: domain
        };
        break;
      }
    }
    if (!foundUser) {
      foundUser = user;
    }
    CacheService.getScriptCache().put('session_' + token, JSON.stringify(foundUser), CACHE_EXPIRATION);
    return { success: true, data: foundUser };
  } catch(e) {
    return { success: false, message: e.message };
  }
}

/**
 * AutoSelect Credit System API per Galeri (Database Spreadsheet Sheet 'Galeri')
 */
function getGalleryAutoSelectCredits(galId) {
  if (!galId) return { success: false, message: 'Kode galeri tidak diberikan. AutoSelect terkunci.', locked: true };
  var cleanGalId = String(galId).trim().toUpperCase();
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Galeri') || ss.getSheetByName('Gallery') || ss.getSheetByName('galeri');
    if (!sheet) return { success: false, message: 'Sheet Galeri tidak ditemukan.', locked: true };
    var map = ensureGalleryVendorColumn(sheet);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['id_galeri']] || '').trim().toUpperCase() === cleanGalId) {
        var raw = map['autoselect_credits'] !== undefined ? data[i][map['autoselect_credits']] : 1;
        var credits = (raw !== '' && raw !== undefined && !isNaN(Number(raw))) ? Number(raw) : 1;
        return {
          success: true,
          galId: cleanGalId,
          clientName: String(data[i][map['nama_client']] || ''),
          eventTitle: String(data[i][map['judul_acara']] || ''),
          credits: credits,
          locked: false
        };
      }
    }
    return { success: false, message: 'Galeri ' + cleanGalId + ' tidak ditemukan di database.', locked: true };
  } catch (e) {
    return { success: false, message: e.message, locked: true };
  }
}

function deductGalleryAutoSelectCredit(galId) {
  if (!galId) return { success: false, message: 'Kode galeri tidak diberikan.', locked: true };
  var cleanGalId = String(galId).trim().toUpperCase();
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Galeri') || ss.getSheetByName('Gallery') || ss.getSheetByName('galeri');
    if (!sheet) return { success: false, message: 'Sheet Galeri tidak ditemukan.', locked: true };
    var map = ensureGalleryVendorColumn(sheet);
    var data = sheet.getDataRange().getValues();
    var rowIndex = -1;
    var currentCredits = 1;
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['id_galeri']] || '').trim().toUpperCase() === cleanGalId) {
        rowIndex = i + 1;
        var raw = map['autoselect_credits'] !== undefined ? data[i][map['autoselect_credits']] : 1;
        currentCredits = (raw !== '' && raw !== undefined && !isNaN(Number(raw))) ? Number(raw) : 1;
        break;
      }
    }
    if (rowIndex === -1) return { success: false, message: 'Galeri tidak ditemukan.', locked: true };
    if (currentCredits <= 0) {
      return { success: false, message: 'Credit AutoSelect untuk galeri ini habis (0 Credit). Silakan tambah credit pada menu Ubah Galeri di Dashboard.', credits: 0, outOfCredits: true };
    }
    var newCredits = currentCredits - 1;
    sheet.getRange(rowIndex, map['autoselect_credits'] + 1).setValue(newCredits);
    SpreadsheetApp.flush();
    logAction('DEDUCT_GAL_CREDIT', cleanGalId, { remaining: newCredits });
    return { success: true, credits: newCredits, message: '1 Credit galeri digunakan. Sisa credit: ' + newCredits + 'x sesi.' };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    try { lock.releaseLock(); } catch(e) {}
  }
}

function setGalleryAutoSelectCredits(arg1, arg2, arg3) {
  var galId = arg1;
  var credits = arg2;
  if (arg3 !== undefined) {
    galId = arg2;
    credits = arg3;
  }
  if (!galId) return { success: false, message: 'Kode galeri tidak diberikan.', locked: true };
  var cleanGalId = String(galId).trim().toUpperCase();
  var numCredits = Math.max(0, parseInt(credits, 10) || 0);
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Galeri') || ss.getSheetByName('Gallery') || ss.getSheetByName('galeri');
    if (!sheet) return { success: false, message: 'Sheet Galeri tidak ditemukan.' };
    var map = ensureGalleryVendorColumn(sheet);
    var data = sheet.getDataRange().getValues();
    var rowIndex = -1;
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['id_galeri']] || '').trim().toUpperCase() === cleanGalId) {
        rowIndex = i + 1;
        break;
      }
    }
    if (rowIndex === -1) return { success: false, message: 'Galeri ' + cleanGalId + ' tidak ditemukan di database spreadsheet.' };
    
    var col = (map['autoselect_credits'] !== undefined) ? map['autoselect_credits'] : (sheet.getLastColumn() - 1);
    sheet.getRange(rowIndex, col + 1).setValue(numCredits);
    SpreadsheetApp.flush();
    
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    logAction('SET_GAL_CREDIT', cleanGalId, { credits: numCredits });
    return { success: true, id_galeri: cleanGalId, autoselect_credits: numCredits, credits: numCredits, message: 'Credit AutoSelect untuk galeri ' + cleanGalId + ' berhasil disimpan di database spreadsheet (' + numCredits + ' Credit).' };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    try { lock.releaseLock(); } catch(e) {}
  }
}

/**
 * Fotografer Backend API (Requires Token)
 */
function getDashboardData(token) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var galData = ss.getSheetByName('Galeri').getDataRange().getValues();
    var jobData = ss.getSheetByName('Job').getDataRange().getValues();
    
    var galMap = getColumnMap(ss.getSheetByName('Galeri'));
    
    var totalGal = 0;
    for(var i=1; i<galData.length; i++) {
       if(galData[i][galMap['id_fotografer']] === user.id_user) totalGal++;
    }

    return { success: true, totalGaleri: totalGal, totalJobs: jobData.length > 1 ? jobData.length -1 : 0 };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function getGalleries(token) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Galeri');
    var map = ensureGalleryVendorColumn(sheet);
    var data = sheet.getDataRange().getValues();
    var results = [];

    for (var i = 1; i < data.length; i++) {
      if(data[i][map['id_fotografer']] === user.id_user) {
        var rawCredits = (map['autoselect_credits'] !== undefined) ? data[i][map['autoselect_credits']] : 1;
        var galCredits = (rawCredits !== '' && rawCredits !== undefined && !isNaN(Number(rawCredits))) ? Number(rawCredits) : 1;
        results.push({
          id_galeri: data[i][map['id_galeri']],
          nama_client: data[i][map['nama_client']],
          judul_acara: data[i][map['judul_acara']],
          link_drive: data[i][map['link_drive']],
          batas_foto: data[i][map['batas_foto']],
          deadline: safeDateFormat(data[i][map['deadline']]),
          tanggal_acara: safeDateFormat(data[i][map['tanggal_acara']]),
          highlight: data[i][map['highlight']],
          email_client: data[i][map['email_client']],
          whatsapp_client: data[i][map['whatsapp_client']],
          whatsapp_vendor: (map['whatsapp_vendor'] !== undefined && data[i][map['whatsapp_vendor']]) ? String(data[i][map['whatsapp_vendor']]) : '',
          nama_vendor: (map['nama_vendor'] !== undefined && data[i][map['nama_vendor']]) ? String(data[i][map['nama_vendor']]) : '',
          kirim_tanpa_drive: (map['kirim_tanpa_drive'] !== undefined && data[i][map['kirim_tanpa_drive']] !== '') ? (data[i][map['kirim_tanpa_drive']] === true || data[i][map['kirim_tanpa_drive']] === 'true' || String(data[i][map['kirim_tanpa_drive']]).toLowerCase() === 'true' || data[i][map['kirim_tanpa_drive']] === 1) : true,
          izin_download: data[i][map['izin_download']] === true || data[i][map['izin_download']] === 'true' || String(data[i][map['izin_download']]).toLowerCase() === 'true' || String(data[i][map['izin_download']]).toLowerCase() === 'ya' || String(data[i][map['izin_download']]) === '1',
          autoselect_credits: galCredits,
          status: data[i][map['status']]
        });
      }
    }
    
    // Sort descending by implicit creation time (row index)
    results.reverse();
    return { success: true, data: results };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function updateGallery(token, payload) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Galeri');
    var map = ensureGalleryVendorColumn(sheet);
    var data = sheet.getDataRange().getValues();
    var rowIndex = -1;

    for (var i = 1; i < data.length; i++) {
      if (data[i][map['id_galeri']] === payload.id_galeri && data[i][map['id_fotografer']] === user.id_user) {
        rowIndex = i + 1;
        break;
      }
    }

    if (rowIndex === -1) return { success: false, message: 'Galeri tidak ditemukan.' };

    if (payload.link_drive !== undefined) {
      var oldLink = String(data[rowIndex - 1][map['link_drive']] || '');
      var cleanLink = sanitizeInput(payload.link_drive.trim());
      sheet.getRange(rowIndex, map['link_drive'] + 1).setValue(cleanLink);
      if (oldLink !== cleanLink && cleanLink) {
        // Hapus file foto lama di sheet Foto agar digantikan foto baru dari link Google Drive baru
        try {
          var photoSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Foto');
          deleteGalleryRows(photoSheet, payload.id_galeri, 'Foto');
        } catch (delErr) {
          Logger.log('Error deleting old photos: ' + delErr);
        }
        importPhotosFromDriveFolder(SpreadsheetApp.getActiveSpreadsheet(), payload.id_galeri, cleanLink);
      }
    }
    if (payload.nama_client !== undefined) sheet.getRange(rowIndex, map['nama_client'] + 1).setValue(sanitizeInput(payload.nama_client));
    if (payload.email_client !== undefined) sheet.getRange(rowIndex, map['email_client'] + 1).setValue(sanitizeInput(payload.email_client));
    if (payload.whatsapp_client !== undefined) sheet.getRange(rowIndex, map['whatsapp_client'] + 1).setValue(sanitizeInput(payload.whatsapp_client));
    if (payload.nama_vendor !== undefined && map['nama_vendor'] !== undefined) {
      sheet.getRange(rowIndex, map['nama_vendor'] + 1).setValue(sanitizeInput(payload.nama_vendor));
    }
    if (payload.whatsapp_vendor !== undefined && map['whatsapp_vendor'] !== undefined) {
      sheet.getRange(rowIndex, map['whatsapp_vendor'] + 1).setValue(sanitizeInput(payload.whatsapp_vendor));
    }
    if (payload.tanggal_acara !== undefined) sheet.getRange(rowIndex, map['tanggal_acara'] + 1).setValue(payload.tanggal_acara);
    if (payload.deadline !== undefined) sheet.getRange(rowIndex, map['deadline'] + 1).setValue(payload.deadline);
    if (payload.highlight !== undefined) sheet.getRange(rowIndex, map['highlight'] + 1).setValue(sanitizeInput(payload.highlight));
    if (payload.batas_foto !== undefined) sheet.getRange(rowIndex, map['batas_foto'] + 1).setValue(parseInt(payload.batas_foto, 10) || 30);
    if (payload.izin_download !== undefined) sheet.getRange(rowIndex, map['izin_download'] + 1).setValue(payload.izin_download === true);
    if (payload.kirim_tanpa_drive !== undefined && map['kirim_tanpa_drive'] !== undefined) {
      sheet.getRange(rowIndex, map['kirim_tanpa_drive'] + 1).setValue(payload.kirim_tanpa_drive === true);
    }
    if (payload.autoselect_credits !== undefined && map['autoselect_credits'] !== undefined) {
      var numCredits = Math.max(0, parseInt(payload.autoselect_credits, 10) || 0);
      sheet.getRange(rowIndex, map['autoselect_credits'] + 1).setValue(numCredits);
    }

    SpreadsheetApp.flush();

    // Hapus script cache agar data di client langsung terperbarui otomatis
    var cleanGalId = String(payload.id_galeri).trim().toUpperCase();
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}

    logAction('UPDATE_GALLERY', user.id_user, payload.id_galeri);
    return { success: true, autoselect_credits: payload.autoselect_credits };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function toggleGalleryDownload(token, galId, allowDownload) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Galeri');
    var data = sheet.getDataRange().getValues();
    var map = getColumnMap(sheet);
    var rowIndex = -1;

    for (var i = 1; i < data.length; i++) {
      if (data[i][map['id_galeri']] === galId && data[i][map['id_fotografer']] === user.id_user) {
        rowIndex = i + 1;
        break;
      }
    }

    if (rowIndex === -1) return { success: false, message: 'Galeri tidak ditemukan.' };

    sheet.getRange(rowIndex, map['izin_download'] + 1).setValue(allowDownload === true);
    var cleanGalId = String(galId).trim().toUpperCase();
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    logAction('TOGGLE_DOWNLOAD', user.id_user, { id_galeri: galId, allowDownload: allowDownload });
    return { success: true, izin_download: allowDownload === true };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

/**
 * Helper fleksibel untuk menemukan sheet tanpa sensitif huruf besar/kecil, spasi, atau variasi nama.
 */
function getSheetByNameFlexible(ss, targetName) {
  if (!ss) return null;
  var sheet = ss.getSheetByName(targetName);
  if (sheet) return sheet;
  var allSheets = ss.getSheets();
  var normalizedTarget = String(targetName || '').toLowerCase().replace(/[^a-z0-9]/g, '');

  // 1. Cek kecocokan nama persis setelah dinormalisasi
  for (var i = 0; i < allSheets.length; i++) {
    var sName = String(allSheets[i].getName() || '').toLowerCase().replace(/[^a-z0-9]/g, '');
    if (sName === normalizedTarget) {
      return allSheets[i];
    }
  }

  // 2. Cek alias / kata kunci umum (misal: 'foto'/'photo', 'seleksi'/'selection')
  var aliases = {
    'foto': ['foto', 'photo', 'photos', 'fotos', 'image', 'images'],
    'seleksi': ['seleksi', 'selection', 'selections', 'pilihan'],
    'galeri': ['galeri', 'gallery', 'galleries']
  };
  var list = aliases[normalizedTarget] || [normalizedTarget];
  for (var j = 0; j < allSheets.length; j++) {
    var cur = String(allSheets[j].getName() || '').toLowerCase().replace(/[^a-z0-9]/g, '');
    for (var a = 0; a < list.length; a++) {
      if (cur === list[a] || cur.indexOf(list[a]) !== -1) {
        return allSheets[j];
      }
    }
  }
  return null;
}

/**
 * Menghapus seluruh baris yang terkait dengan galId dari sheet tertentu.
 * Menggunakan contiguous block range deletion dari baris terbawah ke atas.
 * Menjamin baris-baris data benar-benar terhapus fisik dari spreadsheet
 * dan berjalan sangat cepat tanpa timeout.
 */
function deleteGalleryRows(sheet, galId, sheetType) {
  if (!sheet) return 0;
  var lastRow = sheet.getLastRow();
  if (lastRow <= 1) return 0;
  var lastCol = sheet.getLastColumn();
  if (lastCol < 1) return 0;

  var data = sheet.getRange(1, 1, lastRow, lastCol).getValues();
  if (!data || data.length <= 1) return 0;

  var headers = data[0];
  var targetId = String(galId || '').replace(/^'+/, '').trim().toLowerCase();
  if (!targetId) return 0;

  // Cari kolom id_galeri dan id_foto dari header
  var galColIdx = -1;
  var photoColIdx = -1;
  for (var c = 0; c < headers.length; c++) {
    var h = String(headers[c] || '').toLowerCase().replace(/[^a-z0-9]/g, '');
    if (h === 'idgaleri' || h === 'idgallery' || h === 'galeri' || h === 'gallery') {
      galColIdx = c;
    }
    if (h === 'idfoto' || h === 'idphoto') {
      photoColIdx = c;
    }
  }

  // Fallback index kolom standar
  if (galColIdx === -1) {
    if (sheetType === 'Foto' || sheetType === 'Seleksi') galColIdx = 1;
    else if (sheetType === 'Galeri') galColIdx = 0;
  }
  if (photoColIdx === -1 && sheetType === 'Foto') {
    photoColIdx = 0;
  }

  var rowsToDelete = [];
  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    var isMatch = false;

    // 1. Cek nilai di kolom id_galeri jika terdeteksi
    if (galColIdx !== -1) {
      var val = String(row[galColIdx] || '').replace(/^'+/, '').trim().toLowerCase();
      if (val === targetId) isMatch = true;
    }

    // 2. Cek kolom id_foto jika ada (misal: 'GAL123_F1_...')
    if (!isMatch && photoColIdx !== -1 && row[photoColIdx]) {
      var pId = String(row[photoColIdx] || '').replace(/^'+/, '').trim().toLowerCase();
      if (pId === targetId || pId.indexOf(targetId + '_') === 0 || pId.indexOf(targetId + '-') === 0) {
        isMatch = true;
      }
    }

    // 3. Fallback pencocokan fleksibel di 3 kolom pertama
    if (!isMatch) {
      for (var col = 0; col < Math.min(row.length, 3); col++) {
        var cellStr = String(row[col] || '').replace(/^'+/, '').trim().toLowerCase();
        if (cellStr === targetId || (cellStr.indexOf(targetId + '_') === 0)) {
          isMatch = true;
          break;
        }
      }
    }

    if (isMatch) {
      rowsToDelete.push(i + 1); // 1-indexed row number di sheet
    }
  }

  if (rowsToDelete.length === 0) return 0;

  // Kelompokkan baris berurutan menjadi ranges dari bawah ke atas
  // Contoh: [2, 3, 4, 10, 11] -> range 10 len 2, range 2 len 3
  var ranges = [];
  var curStart = rowsToDelete[rowsToDelete.length - 1];
  var curCount = 1;

  for (var r = rowsToDelete.length - 2; r >= 0; r--) {
    var rNum = rowsToDelete[r];
    if (rNum === curStart - 1) {
      curStart = rNum;
      curCount++;
    } else {
      ranges.push({ start: curStart, count: curCount });
      curStart = rNum;
      curCount = 1;
    }
  }
  ranges.push({ start: curStart, count: curCount });

  // Eksekusi penghapusan blok baris dari bawah ke atas dengan fallback
  try {
    for (var k = 0; k < ranges.length; k++) {
      sheet.deleteRows(ranges[k].start, ranges[k].count);
    }
  } catch(delErr) {
    // Fallback bila deleteRows dibatasi spreadsheet: filter data dan tulis ulang
    var keptRows = [headers];
    var deleteSet = {};
    for (var d = 0; d < rowsToDelete.length; d++) deleteSet[rowsToDelete[d] - 1] = true;
    for (var idx = 1; idx < data.length; idx++) {
      if (!deleteSet[idx]) keptRows.push(data[idx]);
    }
    sheet.clearContents();
    if (keptRows.length > 0 && keptRows[0].length > 0) {
      sheet.getRange(1, 1, keptRows.length, keptRows[0].length).setValues(keptRows);
    }
  }

  SpreadsheetApp.flush();
  return rowsToDelete.length;
}

function deleteGallery(token, galId) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(15000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var targetId = String(galId || '').replace(/^'+/, '').trim();
    if (!targetId) return { success: false, message: 'ID Galeri tidak valid.' };

    var galSheet = getSheetByNameFlexible(ss, 'Galeri');
    if (!galSheet) return { success: false, message: 'Sheet Galeri tidak ditemukan.' };

    var galData = galSheet.getDataRange().getValues();
    var galHeaders = galData[0] || [];
    var galIdCol = 0;
    var fotograferCol = 1;

    for (var c = 0; c < galHeaders.length; c++) {
      var h = String(galHeaders[c] || '').toLowerCase().replace(/[^a-z0-9]/g, '');
      if (h === 'idgaleri' || h === 'idgallery' || h === 'galeri') galIdCol = c;
      if (h === 'idfotografer' || h === 'fotografer') fotograferCol = c;
    }

    var found = false;
    var normTarget = targetId.toLowerCase();

    for (var i = 1; i < galData.length; i++) {
      var rowGalId = String(galData[i][galIdCol] || '').replace(/^'+/, '').trim().toLowerCase();
      if (rowGalId === normTarget) {
        var rowFotografer = String(galData[i][fotograferCol] || '').replace(/^'+/, '').trim();
        var curUser = String(user.id_user || '').replace(/^'+/, '').trim();
        if (rowFotografer === curUser || !rowFotografer || user.role === 'Fotografer' || user.role === 'Admin' || user.role === 'PRO') {
          found = true;
          break;
        }
      }
    }

    if (!found) {
      return { success: false, message: 'Galeri tidak ditemukan atau Anda tidak memiliki akses untuk menghapus.' };
    }

    // 1. Hapus seluruh baris foto terkait dari sheet 'Foto'
    var deletedPhotoCount = 0;
    try {
      var photoSheet = getSheetByNameFlexible(ss, 'Foto');
      if (photoSheet) {
        deletedPhotoCount = deleteGalleryRows(photoSheet, targetId, 'Foto');
      }
    } catch (ePhoto) {
      Logger.log('Gagal menghapus baris di sheet Foto: ' + ePhoto.message);
    }

    // 2. Hapus seluruh baris seleksi & catatan foto terkait dari sheet 'Seleksi'
    var deletedSelCount = 0;
    try {
      var selSheet = getSheetByNameFlexible(ss, 'Seleksi');
      if (selSheet) {
        deletedSelCount = deleteGalleryRows(selSheet, targetId, 'Seleksi');
      }
    } catch (eSel) {
      Logger.log('Gagal menghapus baris di sheet Seleksi: ' + eSel.message);
    }

    // 3. Hapus baris data galeri dari sheet 'Galeri'
    var deletedGalCount = 0;
    try {
      deletedGalCount = deleteGalleryRows(galSheet, targetId, 'Galeri');
    } catch (eGal) {
      Logger.log('Gagal menghapus baris di sheet Galeri: ' + eGal.message);
    }

    // 4. Bersihkan Cache Google Apps Script
    try {
      CacheService.getScriptCache().remove('drive_synced_' + targetId);
    } catch(cErr) {}

    SpreadsheetApp.flush();

    logAction('DELETE_GALLERY', user.id_user, {
      id_galeri: targetId,
      galeri_deleted: deletedGalCount,
      photos_deleted: deletedPhotoCount,
      selections_deleted: deletedSelCount
    });

    var msg = 'Galeri berhasil dihapus.';
    if (deletedPhotoCount > 0 || deletedSelCount > 0) {
      msg = 'Galeri, ' + deletedPhotoCount + ' foto di sheet Foto, dan ' + deletedSelCount + ' data seleksi berhasil dihapus dari spreadsheet.';
    }

    return {
      success: true,
      message: msg,
      galeri_deleted: deletedGalCount,
      photos_deleted: deletedPhotoCount,
      selections_deleted: deletedSelCount
    };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function extractDriveId(url) {
  if (!url) return '';
  var str = String(url).trim();
  // 1. ?id= or &id=
  var mId = str.match(/[?&]id=([-\w]{15,})/i);
  if (mId) return mId[1];
  // 2. /folders/ID
  var mFolder = str.match(/\/folders\/([-\w]{15,})/i);
  if (mFolder) return mFolder[1];
  // 3. /file/d/ID or /d/ID
  var mD = str.match(/\/d\/([-\w]{15,})/i);
  if (mD) return mD[1];
  // 4. General match for 25+ alphanumeric characters
  var mGeneral = str.match(/([-\w]{25,})/);
  if (mGeneral) return mGeneral[1];
  // 5. Match 15+ alphanumeric
  var mShort = str.match(/([-\w]{15,})/);
  return mShort ? mShort[1] : '';
}

function isDriveImageFile(file) {
  try {
    var name = file.getName();
    // Fast check: match file extension first to avoid costly getMimeType() remote RPC call
    if (/\.(jpe?g|png|webp|gif|bmp|heic|heif|cr2|cr3|nef|arw|dng|raw|tif|tiff)$/i.test(name)) {
      return true;
    }
    var mime = (file.getMimeType() || '').toLowerCase();
    return mime.indexOf('image/') === 0;
  } catch (e) {
    return false;
  }
}

function collectDriveImageFiles(folder, fileList, depth, pathSegments, rootFolderName) {
  if (depth > 6) return;
  pathSegments = pathSegments || [];
  try {
    var folderName = folder.getName();
    if (depth === 0 && !rootFolderName) {
      rootFolderName = folderName;
    }

    // For depth 0 (root folder), path is empty.
    // For depth >= 1, path is [subfolder1, subfolder2, ...]
    var currentPath = (depth === 0) ? [] : pathSegments.concat([folderName]);
    var folderLabel = (currentPath.length > 0) ? currentPath.join(' / ') : 'Folder Utama';

    var files = folder.getFiles();
    while (files.hasNext()) {
      var file = files.next();
      if (isDriveImageFile(file)) {
        fileList.push({
          file: file,
          name: file.getName(),
          id: file.getId(),
          folderName: folderLabel,
          folderPath: currentPath.join(' / '),
          folderLevel: depth
        });
      }
    }

    var subFolders = folder.getFolders();
    while (subFolders.hasNext()) {
      var sub = subFolders.next();
      collectDriveImageFiles(sub, fileList, depth + 1, currentPath, rootFolderName);
    }
  } catch (e) {
    Logger.log('Error scanning folder: ' + e);
  }
}

function importPhotosFromDriveFolder(ss, galId, linkDrive) {
  if (!linkDrive) return { newCount: 0, updatedCount: 0 };
  var driveId = extractDriveId(linkDrive);
  if (!driveId) return { newCount: 0, updatedCount: 0 };

  var newPhotosCount = 0;
  var updatedFolderCount = 0;

  try {
    var photoSheet = ss.getSheetByName('Foto');
    var photoMap = ensurePhotoFolderColumn(photoSheet);
    var photoData = photoSheet.getDataRange().getValues();
    var folderColIdx = photoMap['nama_folder']; // 0-based column index
    
    // Check existing files and remove any dummy picsum rows if present
    var rowsToDelete = [];
    var existingDriveIdToRow = {};
    var existingFileNameToRow = {};
    var maxNomorFoto = 0;

    for (var j = 1; j < photoData.length; j++) {
      if (photoData[j][photoMap['id_galeri']] === galId) {
        var existingUrl = String(photoData[j][photoMap['url_foto']] || '');
        if (existingUrl.indexOf('picsum.photos') !== -1 || existingUrl.indexOf('via.placeholder') !== -1) {
          rowsToDelete.push(j + 1);
        } else {
          var fName = String(photoData[j][photoMap['nama_file']] || '').trim();
          var dId = extractDriveId(existingUrl);
          var nom = parseInt(photoData[j][photoMap['nomor_foto']]) || 0;
          if (nom > maxNomorFoto) maxNomorFoto = nom;

          if (dId) existingDriveIdToRow[dId] = j;
          if (fName) existingFileNameToRow[fName] = j;
        }
      }
    }

    // Delete dummy rows in reverse order if any
    for (var d = rowsToDelete.length - 1; d >= 0; d--) {
      photoSheet.deleteRow(rowsToDelete[d]);
    }
    if (rowsToDelete.length > 0) {
      photoData = photoSheet.getDataRange().getValues();
      photoMap = ensurePhotoFolderColumn(photoSheet);
      folderColIdx = photoMap['nama_folder'];
    }

    // Collect files from Drive folder (or single file)
    var filesList = [];
    try {
      var folder = DriveApp.getFolderById(driveId);
      collectDriveImageFiles(folder, filesList, 0, []);
    } catch (folderErr) {
      try {
        var singleFile = DriveApp.getFileById(driveId);
        if (isDriveImageFile(singleFile)) {
          filesList.push({
            file: singleFile,
            name: singleFile.getName(),
            id: singleFile.getId(),
            folderName: 'Folder Utama',
            folderPath: '',
            folderLevel: 0
          });
        }
      } catch (fileErr) {
        Logger.log('Drive access error: ' + fileErr);
      }
    }

    // Sort files naturally by folder and name
    filesList.sort(function(a, b) {
      var folderComp = (a.folderName || '').localeCompare(b.folderName || '', undefined, { numeric: true, sensitivity: 'base' });
      if (folderComp !== 0) return folderComp;
      var nameA = a.name || (a.file ? a.file.getName() : '');
      var nameB = b.name || (b.file ? b.file.getName() : '');
      return nameA.localeCompare(nameB, undefined, { numeric: true, sensitivity: 'base' });
    });

    // Build lookup maps for folder placement from Drive scan
    var driveFolderByFileId = {};
    var driveFolderByFileName = {};
    for (var f = 0; f < filesList.length; f++) {
      var item = filesList[f];
      var fId = item.id || (item.file ? item.file.getId() : '');
      var fName = item.name || (item.file ? item.file.getName() : '');
      var fFolder = item.folderName || 'Folder Utama';
      if (fId) driveFolderByFileId[fId] = fFolder;
      if (fName) driveFolderByFileName[fName] = fFolder;
    }

    // 1. FAST BATCH UPDATE FOR EXISTING PHOTOS (Single batch write to Google Sheets)
    var hasFolderUpdates = false;
    var totalRows = photoData.length - 1; // excluding header
    if (totalRows > 0 && folderColIdx !== undefined) {
      var folderColValues = [];
      for (var r = 1; r < photoData.length; r++) {
        var curVal = String(photoData[r][folderColIdx] || '').trim();
        var rowGalId = photoData[r][photoMap['id_galeri']];

        if (rowGalId === galId) {
          var rUrl = String(photoData[r][photoMap['url_foto']] || '');
          var rDriveId = extractDriveId(rUrl);
          var rFileName = String(photoData[r][photoMap['nama_file']] || '').trim();

          var targetFolder = (rDriveId && driveFolderByFileId[rDriveId]) 
            ? driveFolderByFileId[rDriveId] 
            : (driveFolderByFileName[rFileName] || '');

          if (targetFolder && targetFolder !== curVal) {
            curVal = targetFolder;
            hasFolderUpdates = true;
            updatedFolderCount++;
          }
        }
        folderColValues.push([curVal || 'Folder Utama']);
      }

      if (hasFolderUpdates && folderColValues.length > 0) {
        photoSheet.getRange(2, folderColIdx + 1, folderColValues.length, 1).setValues(folderColValues);
      }
    }

    // 2. FAST BATCH INSERT FOR NEW PHOTOS
    var newRows = [];
    var currentNum = maxNomorFoto;

    for (var f = 0; f < filesList.length; f++) {
      var item = filesList[f];
      var fId = item.id || (item.file ? item.file.getId() : '');
      var fName = item.name || (item.file ? item.file.getName() : '');
      var fFolder = item.folderName || 'Folder Utama';

      var exists = (fId && existingDriveIdToRow[fId] !== undefined) || 
                   (fName && existingFileNameToRow[fName] !== undefined);

      if (!exists) {
        currentNum++;
        var photoId = galId + '_F' + currentNum + '_' + Utilities.getUuid().split('-')[0].toUpperCase();
        var fileUrl = 'https://drive.google.com/thumbnail?id=' + fId + '&sz=w1200';
        newRows.push([photoId, galId, fName, fileUrl, currentNum, fFolder]);
        existingDriveIdToRow[fId] = true;
        existingFileNameToRow[fName] = true;
        newPhotosCount++;
      }
    }

    if (newRows.length > 0) {
      photoSheet.getRange(photoSheet.getLastRow() + 1, 1, newRows.length, newRows[0].length).setValues(newRows);
    }
  } catch (driveErr) {
    Logger.log('Error importing from Drive: ' + driveErr.message);
  }

  return { newCount: newPhotosCount, updatedCount: updatedFolderCount };
}

function rescanGalleryDrive(token, galId) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var galSheet = ss.getSheetByName('Galeri');
    var galData = galSheet.getDataRange().getValues();
    var galMap = getColumnMap(galSheet);
    var galRow = null;

    for (var i = 1; i < galData.length; i++) {
      if (galData[i][galMap['id_galeri']] === galId && galData[i][galMap['id_fotografer']] === user.id_user) {
        galRow = galData[i];
        break;
      }
    }

    if (!galRow) return { success: false, message: 'Galeri tidak ditemukan.' };

    var linkDrive = galRow[galMap['link_drive']];
    var syncResult = importPhotosFromDriveFolder(ss, galId, linkDrive);

    var added = syncResult ? (syncResult.newCount || 0) : 0;
    var updated = syncResult ? (syncResult.updatedCount || 0) : 0;

    var msg = 'Sinkronisasi Google Drive berhasil! ';
    if (added > 0 && updated > 0) {
      msg += added + ' foto baru dimuat dan ' + updated + ' foto diperbarui foldernya.';
    } else if (added > 0) {
      msg += added + ' foto baru berhasil dimuat dari Google Drive.';
    } else if (updated > 0) {
      msg += updated + ' foto berhasil diperbarui foldernya sesuai Google Drive.';
    } else {
      msg += 'Semua foto dan folder Google Drive sudah sinkron.';
    }

    var cleanGalId = String(galId).trim().toUpperCase();
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}

    logAction('RESCAN_DRIVE', user.id_user, { id_galeri: galId, added: added, updated: updated });
    return { success: true, message: msg, added: added, updated: updated };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function createGallery(token, payload) {
  var user = validateSession(token);
  if (!user) return { success: false, message: 'Session expired', sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Galeri');
    var map = ensureGalleryVendorColumn(sheet);
    var id = 'GAL' + Utilities.getUuid().split('-')[0].toUpperCase();
    
    // Defaulting title from client name for simplicity in this version
    var judul = payload.nama_client + " Gallery";

    sheet.appendRow([
      id,
      user.id_user,
      sanitizeInput(payload.nama_client),
      sanitizeInput(judul),
      sanitizeInput(payload.link_drive),
      parseInt(payload.batas_foto) || 50,
      payload.deadline,
      payload.tanggal_acara,
      sanitizeInput(payload.highlight),
      sanitizeInput(payload.email_client || ''),
      sanitizeInput(payload.whatsapp_client),
      payload.izin_download === true,
      'Dibuat',
      sanitizeInput(payload.whatsapp_vendor || ''),
      sanitizeInput(payload.nama_vendor || ''),
      payload.kirim_tanpa_drive !== false
    ]);
    
    var lastRowCreated = sheet.getLastRow();
    if (map['autoselect_credits'] !== undefined) {
      var initialCredits = (payload.autoselect_credits !== undefined && !isNaN(parseInt(payload.autoselect_credits, 10))) ? Math.max(0, parseInt(payload.autoselect_credits, 10)) : 1;
      sheet.getRange(lastRowCreated, map['autoselect_credits'] + 1).setValue(initialCredits);
      SpreadsheetApp.flush();
    }
    
    // Automatically import photos from Google Drive folder on creation
    var importedCount = importPhotosFromDriveFolder(ss, id, payload.link_drive);

    logAction('CREATE_GALLERY', user.id_user, { id_galeri: id, photos_imported: importedCount });
    return { success: true, id: id, photos_imported: importedCount };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

/**
 * Mengurutkan foto dari nomor nama file terbaru sampai terlama (descending).
 * Contoh: IMG_0150.JPG > IMG_0010.JPG > IMG_0001.JPG
 */
function sortPhotosNewestFirst(photos) {
  if (!photos || !Array.isArray(photos)) return photos || [];
  return photos.sort(function(a, b) {
    var nameA = String((a && a.nama_file) || '');
    var nameB = String((b && b.nama_file) || '');
    var numA = -1;
    var numB = -1;
    var matchA = nameA.match(/\d+/g);
    var matchB = nameB.match(/\d+/g);
    if (matchA && matchA.length > 0) {
      numA = parseInt(matchA[matchA.length - 1], 10);
    }
    if (matchB && matchB.length > 0) {
      numB = parseInt(matchB[matchB.length - 1], 10);
    }

    if (numA !== -1 && numB !== -1 && numA !== numB) {
      return numB - numA; // Descending: terbaru (nomor terbesar) ke terlama
    }
    if (numA !== -1 && numB === -1) return -1;
    if (numA === -1 && numB !== -1) return 1;

    var cmp = nameB.localeCompare(nameA, undefined, { numeric: true, sensitivity: 'base' });
    if (cmp !== 0) return cmp;

    return ((b && b.nomor_foto) || 0) - ((a && a.nomor_foto) || 0);
  });
}

/**
 * Client Public API (No Token Required)
 */
function getPublicGallery(galId) {
  try {
    if (!galId) return { success: false, message: 'Kode galeri tidak diberikan.' };
    var cleanGalId = String(galId).trim().toUpperCase();

    // 1. Cek cache respons galeri terlebih dahulu untuk respon instan (< 100ms)
    var cache = CacheService.getScriptCache();
    var cacheKey = 'pub_gal_' + cleanGalId;
    var cachedData = cache.get(cacheKey);
    if (cachedData) {
      try {
        var parsed = JSON.parse(cachedData);
        if (parsed && parsed.success) return parsed;
      } catch (cErr) {}
    }

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var galSheet = ss.getSheetByName('Galeri');
    var galData = galSheet ? galSheet.getDataRange().getValues() : [];
    if (galData.length <= 1) return { success: false, message: 'Galeri belum tersedia.' };
    
    var galMap = getMapFromHeaders(galData[0]);
    if (galMap['whatsapp_vendor'] === undefined || galMap['nama_vendor'] === undefined) {
      galMap = ensureGalleryVendorColumn(galSheet, galMap);
      galData = galSheet.getDataRange().getValues();
    }
    
    var gallery = null;
    for (var i = 1; i < galData.length; i++) {
      var rowId = String(galData[i][galMap['id_galeri']] || '').trim().toUpperCase();
      if (rowId === cleanGalId) {
        gallery = {
          id_galeri: galData[i][galMap['id_galeri']],
          nama_client: galData[i][galMap['nama_client']],
          judul_acara: galData[i][galMap['judul_acara']],
          link_drive: galData[i][galMap['link_drive']],
          highlight: galData[i][galMap['highlight']],
          batas_foto: galData[i][galMap['batas_foto']],
          deadline: safeDateFormat(galData[i][galMap['deadline']]),
          whatsapp_client: galData[i][galMap['whatsapp_client']],
          whatsapp_vendor: (galMap['whatsapp_vendor'] !== undefined && galData[i][galMap['whatsapp_vendor']]) ? String(galData[i][galMap['whatsapp_vendor']]) : '',
          nama_vendor: (galMap['nama_vendor'] !== undefined && galData[i][galMap['nama_vendor']]) ? String(galData[i][galMap['nama_vendor']]) : '',
          kirim_tanpa_drive: (galMap['kirim_tanpa_drive'] !== undefined && galData[i][galMap['kirim_tanpa_drive']] !== '') ? (galData[i][galMap['kirim_tanpa_drive']] === true || galData[i][galMap['kirim_tanpa_drive']] === 'true' || String(galData[i][galMap['kirim_tanpa_drive']]).toLowerCase() === 'true' || galData[i][galMap['kirim_tanpa_drive']] === 1) : true,
          izin_download: galData[i][galMap['izin_download']] === true || galData[i][galMap['izin_download']] === 'true' || String(galData[i][galMap['izin_download']]).toLowerCase() === 'true' || String(galData[i][galMap['izin_download']]).toLowerCase() === 'ya' || String(galData[i][galMap['izin_download']]) === '1',
          status: galData[i][galMap['status']]
        };
        break;
      }
    }

    if (!gallery) return { success: false, message: 'Galeri tidak ditemukan. Pastikan kode atau link galeri sudah benar.' };

    // Fetch photos
    var photoSheet = ss.getSheetByName('Foto');
    var photoData = photoSheet ? photoSheet.getDataRange().getValues() : [];
    var photoMap = (photoData.length > 0) ? getMapFromHeaders(photoData[0]) : {};
    if (photoData.length > 0 && photoMap['nama_folder'] === undefined) {
      photoMap = ensurePhotoFolderColumn(photoSheet, photoMap);
      photoData = photoSheet.getDataRange().getValues();
    }
    var photos = [];
    
    for (var j = 1; j < photoData.length; j++) {
      var pGalId = String(photoData[j][photoMap['id_galeri']] || '').trim().toUpperCase();
      if (pGalId === cleanGalId) {
        var rawUrl = String(photoData[j][photoMap['url_foto']] || '');
        if (rawUrl.indexOf('picsum.photos') !== -1 || rawUrl.indexOf('via.placeholder') !== -1) {
          continue; // Filter out dummy photos
        }
        var driveId = extractDriveId(rawUrl);
        var displayUrl = (driveId && (rawUrl.indexOf('drive.google.com') !== -1 || rawUrl.indexOf('google.com') !== -1 || rawUrl.indexOf('googleusercontent.com') !== -1))
          ? 'https://drive.google.com/thumbnail?id=' + driveId + '&sz=w1200'
          : rawUrl;

        var rawFolder = (photoMap['nama_folder'] !== undefined && photoData[j][photoMap['nama_folder']])
          ? String(photoData[j][photoMap['nama_folder']]).trim()
          : '';

        photos.push({
          id_foto: photoData[j][photoMap['id_foto']],
          nama_file: photoData[j][photoMap['nama_file']],
          url_foto: displayUrl,
          id_drive: driveId,
          nomor_foto: photoData[j][photoMap['nomor_foto']] || photos.length + 1,
          nama_folder: rawFolder || 'Folder Utama'
        });
      }
    }
    
    // HANYA scan Google Drive jika sheet Foto benar-benar kosong (0 foto) untuk menghindari loading lama
    var needsDriveCheck = (photos.length === 0 && gallery.link_drive);

    if (needsDriveCheck) {
      importPhotosFromDriveFolder(ss, gallery.id_galeri, gallery.link_drive);

      // Re-query photos setelah import pertama
      photos = [];
      var refreshedPhotoData = photoSheet.getDataRange().getValues();
      photoMap = (refreshedPhotoData.length > 0) ? getMapFromHeaders(refreshedPhotoData[0]) : {};
      for (var m = 1; m < refreshedPhotoData.length; m++) {
        var rGalId = String(refreshedPhotoData[m][photoMap['id_galeri']] || '').trim().toUpperCase();
        if (rGalId === cleanGalId) {
          var rUrl = String(refreshedPhotoData[m][photoMap['url_foto']] || '');
          if (rUrl.indexOf('picsum.photos') !== -1 || rUrl.indexOf('via.placeholder') !== -1) continue;
          var dId = extractDriveId(rUrl);
          var dispUrl = (dId && (rUrl.indexOf('drive.google.com') !== -1 || rUrl.indexOf('google.com') !== -1 || rUrl.indexOf('googleusercontent.com') !== -1))
            ? 'https://drive.google.com/thumbnail?id=' + dId + '&sz=w1200'
            : rUrl;

          var refFolder = (photoMap['nama_folder'] !== undefined && refreshedPhotoData[m][photoMap['nama_folder']])
            ? String(refreshedPhotoData[m][photoMap['nama_folder']]).trim()
            : 'Folder Utama';

          photos.push({
            id_foto: refreshedPhotoData[m][photoMap['id_foto']],
            nama_file: refreshedPhotoData[m][photoMap['nama_file']],
            url_foto: dispUrl,
            id_drive: dId,
            nomor_foto: refreshedPhotoData[m][photoMap['nomor_foto']] || photos.length + 1,
            nama_folder: refFolder || 'Folder Utama'
          });
        }
      }
    }

    // Urutkan foto dari nomor nama file yang terbaru sampai yang terlama (descending)
    sortPhotosNewestFirst(photos);

    // Fetch existing selections if any
    var selections = [];
    try {
      var selSheet = ss.getSheetByName('Seleksi');
      var selData = selSheet ? selSheet.getDataRange().getValues() : [];
      if (selData.length > 1) {
        var selMap = getMapFromHeaders(selData[0]);
        for (var s = 1; s < selData.length; s++) {
          var sGalId = String(selData[s][selMap['id_galeri']] || '').trim().toUpperCase();
          if (sGalId === cleanGalId) {
            selections.push({
              id_foto: selData[s][selMap['id_foto']],
              pesan: selData[s][selMap['pesan_client']] || '',
              tanggal_pilih: safeDateFormat(selData[s][selMap['tanggal_pilih']])
            });
          }
        }
      }
    } catch (selErr) {}


    var result = {
      success: true,
      gallery: gallery,
      photos: photos,
      selections: selections,
      driveConnected: !!gallery.link_drive,
      driveFolderId: extractDriveId(gallery.link_drive)
    };

    // Cache di ScriptCache agar pembukaan galeri berikutnya instan
    try {
      var jsonStr = JSON.stringify(result);
      if (jsonStr.length < 95000) {
        cache.put(cacheKey, jsonStr, 1800); // 30 menit
      }
    } catch (cErr) {}

    return result;
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function submitClientSelection(galId, selections, options) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(15000);
    var cleanGalId = String(galId || '').trim().toUpperCase();
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    
    // Update gallery status
    var galSheet = ss.getSheetByName('Galeri');
    var galMap = ensureGalleryVendorColumn(galSheet);
    var galData = galSheet.getDataRange().getValues();
    var targetRow = -1;
    var realGalId = galId;
    var gallery = null;
    for(var i=1; i<galData.length; i++) {
      var rowGId = String(galData[i][galMap['id_galeri']] || '').trim().toUpperCase();
      if(rowGId === cleanGalId) {
         targetRow = i + 1;
         realGalId = galData[i][galMap['id_galeri']];
         gallery = {
           id_galeri: realGalId,
           nama_client: galData[i][galMap['nama_client']] || 'Klien',
           judul_acara: galData[i][galMap['judul_acara']] || 'Acara',
           link_drive: galData[i][galMap['link_drive']] || '',
           status: galData[i][galMap['status']] || 'Aktif',
           kirim_tanpa_drive: (galMap['kirim_tanpa_drive'] !== undefined && galData[i][galMap['kirim_tanpa_drive']] !== '') ? (galData[i][galMap['kirim_tanpa_drive']] === true || galData[i][galMap['kirim_tanpa_drive']] === 'true' || galData[i][galMap['kirim_tanpa_drive']] === 1) : true
         };
         break;
      }
    }
    if(targetRow === -1 || !gallery) throw new Error("Galeri invalid.");

    // Cek apakah sudah pernah selesai/terkirim sebelumnya (Client tidak dapat mengirim lagi)
    if (gallery.status === 'Selesai') {
      return { success: false, message: 'Pilihan foto untuk galeri ini sudah dikirim sebelumnya dan statusnya telah dikunci. Anda tidak dapat mengirim ulang.' };
    }

    galSheet.getRange(targetRow, galMap['status']+1).setValue('Selesai');

    // Insert selections (bersihkan seleksi lama jika ada untuk galeri ini sebelum simpan final)
    var selSheet = ss.getSheetByName('Seleksi');
    var selData = selSheet.getDataRange().getValues();
    var selMap = getColumnMap(selSheet);
    for (var d = selData.length - 1; d >= 1; d--) {
      var dGId = String(selData[d][selMap['id_galeri']] || '').trim().toUpperCase();
      if (dGId === cleanGalId) {
        selSheet.deleteRow(d + 1);
      }
    }

    var now = new Date().toISOString();
    var rows = [];
    for(var j=0; j<selections.length; j++) {
       var selId = 'SEL' + Utilities.getUuid().split('-')[0].toUpperCase();
       rows.push([selId, realGalId, sanitizeInput(selections[j].id_foto), sanitizeInput(selections[j].pesan || ''), now]);
    }
    
    if(rows.length > 0) {
      selSheet.getRange(selSheet.getLastRow() + 1, 1, rows.length, rows[0].length).setValues(rows);
    }

    // Tentukan apakah proses pembuatan folder Drive dilewati (Direct WA tanpa folder Drive)
    var skipDrive = false;
    if (options && typeof options === 'object') {
      if (options.skipDriveFolder !== undefined) {
        skipDrive = !!options.skipDriveFolder;
      }
    } else if (gallery.kirim_tanpa_drive !== undefined) {
      skipDrive = (gallery.kirim_tanpa_drive === true || gallery.kirim_tanpa_drive === 'true' || gallery.kirim_tanpa_drive === 1);
    }

    var driveFolderUrl = '';
    var targetFolderName = '';
    var copiedCount = 0;

    if (!skipDrive) {
      // --- OTOMATIS BUATKAN SUBFOLDER GOOGLE DRIVE UNTUK FOTO TERPILIH ---
      try {
        var parentDriveId = extractDriveId(gallery.link_drive);
        var parentFolder = null;
        if (parentDriveId) {
          try {
            parentFolder = DriveApp.getFolderById(parentDriveId);
          } catch (fErr) {}
        }
        if (!parentFolder) {
          parentFolder = DriveApp.getRootFolder();
        }

        targetFolderName = '[SELEKSI SEMENTARA 3 HARI] - ' + (gallery.nama_client || 'Klien') + ' - ' + (gallery.judul_acara || 'Acara') + ' (' + selections.length + ' Foto)';
        var targetFolder = null;
        var existingSubfolders = parentFolder.getFoldersByName(targetFolderName);
        if (existingSubfolders.hasNext()) {
          targetFolder = existingSubfolders.next();
        } else {
          targetFolder = parentFolder.createFolder(targetFolderName);
        }
        try {
          targetFolder.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
        } catch (shErr) {}

        // Ambil data foto dari sheet Foto untuk mencocokkan id_foto dengan id file Google Drive
        var photoSheet = ss.getSheetByName('Foto');
        var photoData = photoSheet ? photoSheet.getDataRange().getValues() : [];
        var photoMap = getColumnMap(photoSheet);
        var selIds = selections.map(function(s) { return String(s.id_foto).trim(); });

        for (var p = 1; p < photoData.length; p++) {
          var pGalId = String(photoData[p][photoMap['id_galeri']] || '').trim().toUpperCase();
          var pId = String(photoData[p][photoMap['id_foto']] || '').trim();
          if (pGalId === cleanGalId && selIds.indexOf(pId) !== -1) {
            var dUrl = String(photoData[p][photoMap['url_foto']] || '');
            var dId = extractDriveId(dUrl);
            if (dId) {
              try {
                var file = DriveApp.getFileById(dId);
                var fileName = photoData[p][photoMap['nama_file']] || file.getName();
                var existingFiles = targetFolder.getFilesByName(fileName);
                if (!existingFiles.hasNext()) {
                  file.makeCopy(fileName, targetFolder);
                }
                copiedCount++;
              } catch (cpErr) {}
            }
          }
        }

        if (targetFolder) {
          driveFolderUrl = targetFolder.getUrl();
          // Catat folder sementara untuk auto-delete setelah 3 hari
          recordTempFolder(targetFolder.getId(), realGalId, targetFolderName, driveFolderUrl, 3);
          setupDailyCleanupTrigger();
        }
      } catch (driveErr) {
        logAction('DRIVE_AUTO_COPY_ERR', cleanGalId, driveErr.message);
      }

      // Jalankan pembersihan jika ada folder lama yang sudah lewat 3 hari
      try { cleanupExpiredTempFolders(); } catch(cleanErr) {}
    }

    logAction('CLIENT_SUBMIT', 'Client_' + cleanGalId, 'Total: ' + rows.length + ', SkipDrive: ' + skipDrive + ', DriveCopied: ' + copiedCount);
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    
    return { 
      success: true, 
      driveFolderUrl: driveFolderUrl,
      folderName: targetFolderName,
      copiedCount: copiedCount,
      totalCount: rows.length,
      skippedDrive: skipDrive
    };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function saveSingleClientSelection(galId, photoId, note) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var cleanGalId = String(galId || '').trim().toUpperCase();
    var cleanPhotoId = String(photoId || '').trim();
    if (!cleanGalId || !cleanPhotoId) throw new Error("Parameter galId dan photoId wajib diisi.");
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var selSheet = ss.getSheetByName('Seleksi');
    if (!selSheet) throw new Error("Sheet Seleksi tidak ditemukan.");
    var selData = selSheet.getDataRange().getValues();
    var selMap = getColumnMap(selSheet);
    var now = new Date().toISOString();
    var foundRow = -1;
    for (var i = 1; i < selData.length; i++) {
      var rGId = String(selData[i][selMap['id_galeri']] || '').trim().toUpperCase();
      var rPId = String(selData[i][selMap['id_foto']] || '').trim();
      if (rGId === cleanGalId && rPId === cleanPhotoId) {
        foundRow = i + 1;
        break;
      }
    }
    if (foundRow !== -1) {
      if (note !== undefined && note !== null) {
        selSheet.getRange(foundRow, selMap['pesan_client'] + 1).setValue(sanitizeInput(note));
      }
      selSheet.getRange(foundRow, selMap['tanggal_pilih'] + 1).setValue(now);
    } else {
      var selId = 'SEL' + Utilities.getUuid().split('-')[0].toUpperCase();
      selSheet.appendRow([selId, galId, cleanPhotoId, sanitizeInput(note || ''), now]);
    }
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    return { success: true };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function deleteSingleClientSelection(galId, photoId) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var cleanGalId = String(galId || '').trim().toUpperCase();
    var cleanPhotoId = String(photoId || '').trim();
    if (!cleanGalId || !cleanPhotoId) throw new Error("Parameter tidak valid.");
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var selSheet = ss.getSheetByName('Seleksi');
    if (!selSheet) return { success: true };
    var selData = selSheet.getDataRange().getValues();
    var selMap = getColumnMap(selSheet);
    for (var i = selData.length - 1; i >= 1; i--) {
      var rGId = String(selData[i][selMap['id_galeri']] || '').trim().toUpperCase();
      var rPId = String(selData[i][selMap['id_foto']] || '').trim();
      if (rGId === cleanGalId && rPId === cleanPhotoId) {
        selSheet.deleteRow(i + 1);
        break;
      }
    }
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    return { success: true };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function clearClientSelections(galId) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var cleanGalId = String(galId || '').trim().toUpperCase();
    if (!cleanGalId) throw new Error("ID Galeri kosong.");
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var selSheet = ss.getSheetByName('Seleksi');
    if (selSheet) {
      var selData = selSheet.getDataRange().getValues();
      var selMap = getColumnMap(selSheet);
      for (var i = selData.length - 1; i >= 1; i--) {
        var rGId = String(selData[i][selMap['id_galeri']] || '').trim().toUpperCase();
        if (rGId === cleanGalId) {
          selSheet.deleteRow(i + 1);
        }
      }
    }
    // Revert status gallery back to 'Sedang memilih' if it was 'Selesai'
    var galSheet = ss.getSheetByName('Galeri');
    if (galSheet) {
      var galData = galSheet.getDataRange().getValues();
      var galMap = getColumnMap(galSheet);
      for (var j = 1; j < galData.length; j++) {
        var rowGId = String(galData[j][galMap['id_galeri']] || '').trim().toUpperCase();
        if (rowGId === cleanGalId) {
          galSheet.getRange(j + 1, galMap['status'] + 1).setValue('Sedang memilih');
          break;
        }
      }
    }
    try { CacheService.getScriptCache().remove('pub_gal_' + cleanGalId); } catch(cErr) {}
    return { success: true };
  } catch (e) {
    return { success: false, message: e.message };
  } finally {
    lock.releaseLock();
  }
}

function createSelectedPhotosDriveFolder(token, galId) {
  try {
    var user = verifyToken(token);
    if (!user) throw new Error("Sesi berakhir, silakan login kembali.");
    var cleanGalId = String(galId || '').trim().toUpperCase();
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var galSheet = ss.getSheetByName('Galeri');
    var galData = galSheet.getDataRange().getValues();
    var galMap = getColumnMap(galSheet);
    var gallery = null;
    for (var i = 1; i < galData.length; i++) {
      if (String(galData[i][galMap['id_galeri']] || '').trim().toUpperCase() === cleanGalId) {
        gallery = {
          id_galeri: galData[i][galMap['id_galeri']],
          nama_client: galData[i][galMap['nama_client']] || 'Client',
          judul_acara: galData[i][galMap['judul_acara']] || 'Acara',
          link_drive: galData[i][galMap['link_drive']] || ''
        };
        break;
      }
    }
    if (!gallery) throw new Error("Galeri tidak ditemukan.");

    // Ambil daftar id_foto yang dipilih
    var selSheet = ss.getSheetByName('Seleksi');
    var selData = selSheet ? selSheet.getDataRange().getValues() : [];
    var selMap = getColumnMap(selSheet);
    var selectedPhotoIds = [];
    for (var s = 1; s < selData.length; s++) {
      if (String(selData[s][selMap['id_galeri']] || '').trim().toUpperCase() === cleanGalId) {
        selectedPhotoIds.push(String(selData[s][selMap['id_foto']] || '').trim());
      }
    }

    if (selectedPhotoIds.length === 0) {
      throw new Error("Klien belum memilih foto untuk galeri ini.");
    }

    // Ambil detail foto dari sheet Foto
    var photoSheet = ss.getSheetByName('Foto');
    var photoData = photoSheet ? photoSheet.getDataRange().getValues() : [];
    var photoMap = getColumnMap(photoSheet);
    var photosToCopy = [];
    for (var p = 1; p < photoData.length; p++) {
      var pGalId = String(photoData[p][photoMap['id_galeri']] || '').trim().toUpperCase();
      var pId = String(photoData[p][photoMap['id_foto']] || '').trim();
      if (pGalId === cleanGalId && selectedPhotoIds.indexOf(pId) !== -1) {
        var dUrl = String(photoData[p][photoMap['url_foto']] || '');
        var dId = extractDriveId(dUrl);
        photosToCopy.push({
          id_foto: pId,
          nama_file: photoData[p][photoMap['nama_file']] || 'photo.jpg',
          driveId: dId
        });
      }
    }

    // Tentukan folder induk Drive
    var parentDriveId = extractDriveId(gallery.link_drive);
    var parentFolder = null;
    if (parentDriveId) {
      try {
        parentFolder = DriveApp.getFolderById(parentDriveId);
      } catch (err) {}
    }
    if (!parentFolder) {
      parentFolder = DriveApp.getRootFolder();
    }

    // Buat subfolder khusus seleksi: [SELEKSI SEMENTARA 3 HARI] - Nama Client
    var targetFolderName = '[SELEKSI SEMENTARA 3 HARI] - ' + (gallery.nama_client || 'Klien') + ' (' + selectedPhotoIds.length + ' Foto JPG)';
    var targetFolder = null;
    var existingSubfolders = parentFolder.getFoldersByName(targetFolderName);
    if (existingSubfolders.hasNext()) {
      targetFolder = existingSubfolders.next();
    } else {
      targetFolder = parentFolder.createFolder(targetFolderName);
    }

    // Salin foto JPG ke dalam subfolder
    var copiedCount = 0;
    for (var c = 0; c < photosToCopy.length; c++) {
      var item = photosToCopy[c];
      if (item.driveId) {
        try {
          var file = DriveApp.getFileById(item.driveId);
          var filesInTarget = targetFolder.getFilesByName(file.getName());
          if (!filesInTarget.hasNext()) {
            file.makeCopy(file.getName(), targetFolder);
          }
          copiedCount++;
        } catch (copyErr) {}
      }
    }

    if (targetFolder) {
      recordTempFolder(targetFolder.getId(), cleanGalId, targetFolderName, targetFolder.getUrl(), 3);
      setupDailyCleanupTrigger();
    }

    return {
      success: true,
      folderUrl: targetFolder.getUrl(),
      folderName: targetFolderName,
      totalSelected: selectedPhotoIds.length,
      copiedCount: copiedCount,
      message: 'Folder sementara (aktif 3 hari) berhasil disiapkan dengan ' + copiedCount + ' foto JPG.'
    };
  } catch (e) {
    return { success: false, message: e.message };
  }
}
function resetPassword(email) {
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('User');
    if (!sheet) return { success: false, message: 'Database tidak ditemukan.' };
    
    var data = sheet.getDataRange().getValues();
    var map = getColumnMap(sheet);
    var cleanEmail = String(email).trim().toLowerCase();

    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['email']] || '').trim().toLowerCase() === cleanEmail) {
        // Ditemukan user dengan email tsb
        var newPass = Math.random().toString(36).slice(-8); // Generate 8 karakter password
        var hashed = hashPassword(newPass);
        
        // Update password di sheet
        sheet.getRange(i + 1, map['password'] + 1).setValue(hashed);

        // Kirim Email
        var username = data[i][map['username']] || 'admin';
        var name = data[i][map['nama']] || 'Pengguna';
        var subject = "Reset Password - Pilihin Studio";
        var body = "Halo " + name + ",\n\n" +
                   "Password akun Anda telah berhasil direset. Berikut adalah informasi login Anda yang baru:\n\n" +
                   "Username : " + username + "\n" +
                   "Password Baru : " + newPass + "\n\n" +
                   "Silakan login menggunakan password baru tersebut, lalu segera ganti password Anda di menu Pengaturan demi keamanan.\n\n" +
                   "Terima kasih.\nTim Pilihin Studio";
        
        MailApp.sendEmail(cleanEmail, subject, body);

        logAction('RESET_PASSWORD', data[i][map['id_user']], 'Password reset sent to ' + cleanEmail);
        return { success: true, message: 'Password baru telah berhasil dikirim ke email Anda.' };
      }
    }
    return { success: false, message: 'Email tidak ditemukan di sistem kami.' };
  } catch(e) {
    return { success: false, message: 'Gagal mereset password: ' + e.message };
  }
}

/**
 * Catat folder sementara pilihan klien agar otomatis terhapus setelah 3 hari
 */
function recordTempFolder(folderId, galId, folderName, folderUrl, daysValid) {
  try {
    if (!folderId) return;
    var days = Number(daysValid) || 3;
    var now = new Date();
    var expiresAt = new Date(now.getTime() + (days * 24 * 60 * 60 * 1000));
    
    // Set deskripsi di Google Drive folder untuk identifikasi ganda
    try {
      var folder = DriveApp.getFolderById(folderId);
      if (folder) {
        folder.setDescription('TEMPORARY_SELECTION_FOLDER|CREATED:' + now.toISOString() + '|EXPIRES:' + expiresAt.toISOString() + '|GAL_ID:' + galId);
      }
    } catch(dErr) {}

    // Catat ke sheet TempFolder
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('TempFolder');
    if (!sheet) {
      sheet = ss.insertSheet('TempFolder');
      sheet.appendRow(['id_folder', 'id_galeri', 'nama_folder', 'url_folder', 'tanggal_buat', 'tanggal_kadaluarsa', 'status']);
      sheet.setFrozenRows(1);
    }
    sheet.appendRow([
      folderId,
      galId || '',
      folderName || '',
      folderUrl || '',
      now.toISOString(),
      expiresAt.toISOString(),
      'Aktif'
    ]);
  } catch (err) {
    logAction('TEMP_FOLDER_RECORD_ERR', galId, err.message);
  }
}

/**
 * Hapus folder sementara di Google Drive yang sudah lewat dari 3 hari secara otomatis
 */
function cleanupExpiredTempFolders() {
  var deletedCount = 0;
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('TempFolder');
    if (!sheet) return { success: true, deletedCount: 0 };

    var data = sheet.getDataRange().getValues();
    if (data.length <= 1) return { success: true, deletedCount: 0 };

    var map = getColumnMap(sheet);
    var now = new Date();

    for (var i = 1; i < data.length; i++) {
      var status = String(data[i][map['status']] || '').trim();
      if (status !== 'Aktif') continue;

      var expStr = String(data[i][map['tanggal_kadaluarsa']] || '').trim();
      if (!expStr) continue;

      var expDate = new Date(expStr);
      if (isNaN(expDate.getTime())) continue;

      if (now.getTime() >= expDate.getTime()) {
        var folderId = String(data[i][map['id_folder']] || '').trim();
        var folderName = String(data[i][map['nama_folder']] || 'Folder Sementara');
        var galId = String(data[i][map['id_galeri']] || '');

        if (folderId) {
          try {
            var folder = DriveApp.getFolderById(folderId);
            if (folder) {
              folder.setTrashed(true);
              deletedCount++;
              logAction('AUTO_DELETE_TEMP_FOLDER', galId, 'Folder Drive [' + folderName + '] otomatis terhapus setelah 3 hari.');
            }
          } catch (fErr) {
            // Folder mungkin sudah dihapus manual oleh pengguna
          }
        }

        // Tandai status di sheet menjadi Terhapus Otomatis
        sheet.getRange(i + 1, map['status'] + 1).setValue('Terhapus Otomatis (3 Hari)');
      }
    }
  } catch (e) {
    logAction('CLEANUP_TEMP_ERR', 'System', e.message);
  }
  return { success: true, deletedCount: deletedCount };
}

/**
 * Pastikan trigger harian terpasang untuk pembersihan otomatis
 */
function setupDailyCleanupTrigger() {
  try {
    var triggers = ScriptApp.getProjectTriggers();
    for (var i = 0; i < triggers.length; i++) {
      if (triggers[i].getHandlerFunction() === 'cleanupExpiredTempFolders') {
        return; // Sudah terpasang
      }
    }
    ScriptApp.newTrigger('cleanupExpiredTempFolders')
      .timeBased()
      .everyDays(1)
      .atHour(2)
      .create();
  } catch (e) {
    // Jika hak akses script trigger belum diizinkan, opportunistic check saat request webapp tetap aktif
  }
}
